### ISSUE TITLE
Enable nginx to start on boot

### ISSUE THREAD

**Issue by alex-418** [pressbooks/trellis#17]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums
---

**What is the current behavior?**

The nginx service isn't enabled, so it doesn't automatically start on
boot.

**What is the expected or desired behavior?**

ngix service is enabled and starts on boot.

---

## Bug report

Please see https://github.com/roots/trellis/pull/980

Adding this to the end of roles/nginx/tasks/main.yml would resolve it:

```
- name: Enable Nginx to start on boot
  service:
    name: nginx
    enabled: yes
    state: started
    use: service
```
